from AgentApp.graph.state import AgentState
from AgentApp.utils.json_parsing import safe_json_load
import inspect
from AgentApp.initialize_llm import get_llm
from AgentTools.tool_registry import all_tools

def plan_critic_node(state: AgentState):
    
    contracts = extract_relevant_tool_contracts(state["plan"])
    llm = get_llm()
    prompt = f""" 
        You are a plan critic, your responsibility is to make sure the provided plan is consistent in
        terms of dependency chaining, proper tools, right order of execution, correct dependency, and right
        outputs reach the input of the dependent step.

        User goal is:
        {state["user_goal"]}

        Current plan generated by the planner is:
        {state['plan']}

        Retrieved memory:
        {state['retrieved_memory']}

        And the schema of the tools used in this plan is:
        {contracts}

        Evaluate the plan based on the following criteria:
        1. Are all tools existed?
        2. Whether the input schema and input arguments are consistent or not
        3. Whether all reference variables are in the $... format? if they are, are they valid?
        4. Whether the output of a given step provides a logical path to the downstream steps.
        5. Are all "depends_on" in the plan are consistent with the data flow required by the plan?
        6. Is the order of steps logical and results in the user's goal?
        7. Are "type" variables correct?
        8. Are "reasoning_requires" correct based on the fact that the step requires more than just tool calling
        and need interpretation and decision-making that cannot be obtained by tools output alone?
        9. Are there any steps that depend logically on the output of step or steps that its "depends_on" is empty?
        10. Does this plan reach its user's goal?

        Then return only the following JSON and strictly stick to it, if the plan was ok only set valid to True and leave issue parameter as []:

        {{
            "valid": True/False,
            "issues": [
                {{  "step": int,
                    "problem": str,
                    "reason": str,
                    "suggestion": str}}
            ]
        }}

     """
    
    result = llm.invoke(prompt)

    print("\n=== Raw Critic ===")
    print(result.content)

    critic = safe_json_load(result.content)

    if state["plan_origin"] == "planner":
        new_history = state["planning_history"] + [{
            "plan": state["plan"],
            "critic": critic
        }]

        return {
            "critic_comment": critic,
            "planning_history": new_history
        }

    else:
        new_history = state["replanning_history"] + [{
            "plan": state["plan"],
            "critic": critic
        }]

        return {
            "critic_comment": critic,
            "replanning_history": new_history
        }
    

def extract_tool_contract(tool, all_tools):
    related_tool = all_tools[tool]

    if not related_tool:
        return "Not such a tool"
    
    tool_input = related_tool.args_schema.model_json_schema()

    tool_output = inspect.signature(related_tool.func).return_annotation.model_json_schema()

    return {
        "name": tool,
        "input": tool_input,
        "output": tool_output
    }

def extract_relevant_tool_contracts(plan):

    tool_names = set()

    for step in plan:
        if step["type"] == "tool":
            tool_names.add(step["tool"])

    if not tool_names:
        return []

    contracts = []

    for tool_name in tool_names:
        contracts.append({
            "tool_name": tool_name,
            "schema": extract_tool_contract(tool_name, all_tools)
        })

    return contracts

